language: node_js
node_js:
    - "6.10.1"
notifications:
    email: false
sudo: required
services:
    - docker
addons:
    artifacts:
        paths: ./vrt/failures
cache: yarn
install:
    - yarn install
script:
    - yarn test
    - yarn run package
env:
    global:
        IS_CI: true