language: node_js
node_js:
    - "6.4.0"
notifications:
    email: false
sudo: required
services:
    - docker
env:
    global:
        - VIZ_HOME="appserver/static/visualizations/timewrap"
before_install:
    - cd $VIZ_HOME
install:
    - npm install
script:
    - npm test