language: node_js
node_js:
    - "6.4.0"
notifications:
    email: false
sudo: required
services:
    - docker
addons:
    artifacts:
        paths: ./vrt/failures
cache:
    directories:
        - $HOME/.yarn-cache
before_install:
    # Install yarn
    - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
    - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    - sudo apt-get update -qq
    - sudo apt-get install -y -qq yarn
install:
    - yarn install
script:
    - yarn test
    - yarn run package