language: node_js
node_js:
    - "6.4.0"
notifications:
    email: false
sudo: required
services:
    - docker
env:
    global:
        - VIZ_HOME=$(pwd)/appserver/static/visualizations/timewrap
before_install:
    - cd $VIZ_HOME
    - echo $VIZ_HOME
    - docker pull selenium/standalone-chrome:2.53.0
    - docker run --name selenium -d -p 4444:4444 -v $VIZ_HOME/vrt:/vrt selenium/standalone-chrome
    - docker inspect selenium
install:
    - npm install
script:
    - npm test